version: '3'
services:
  python-app:
    image: python:3.11.3
    container_name: my-python-container
    working_dir: /app
    volumes:
      - .:/app
    command: python prueba-docker.py
    ports:
      - "5000:5000"  # Si necesitas exponer puertos